Backport of:

From 5e9c6b9175d66170ef65fc703f2e46788a59ca0c Mon Sep 17 00:00:00 2001
From: SethMichaelLarson <sethmichaellarson@protonmail.com>
Date: Sun, 25 Mar 2018 20:52:13 -0500
Subject: [PATCH] Fix AppEngine connection pool tests

---
 test/appengine/test_gae_manager.py           | 4 ++++
 test/with_dummyserver/test_connectionpool.py | 9 ++++++---
 2 files changed, 10 insertions(+), 3 deletions(-)

Index: python-urllib3-1.13.1/test/with_dummyserver/test_connectionpool.py
===================================================================
--- python-urllib3-1.13.1.orig/test/with_dummyserver/test_connectionpool.py	2019-05-13 15:16:33.925353443 -0400
+++ python-urllib3-1.13.1/test/with_dummyserver/test_connectionpool.py	2019-05-13 15:16:33.925353443 -0400
@@ -18,8 +18,7 @@ from .. import (
     requires_network, onlyPy3, onlyPy26OrOlder,
     TARPIT_HOST,
     VALID_SOURCE_ADDRESSES,
-    INVALID_SOURCE_ADDRESSES,
-    requires_network
+    INVALID_SOURCE_ADDRESSES
 )
 from ..port_helpers import find_unused_port
 from urllib3 import (
@@ -797,7 +796,11 @@ class TestRetry(HTTPDummyServerTestCase)
         headers = {'Authentication': 'foo'}
         retry = Retry(redirect=2, forward_auth_headers_across_hosts=True)
 
-        resp = self.pool.urlopen('GET', url, headers=headers, assert_same_host=False, retries=retry)
+        resp = self.pool.urlopen(
+            'GET', url, headers=headers,
+            assert_same_host=False,
+            retries=retry
+        )
 
         self.assertEqual(resp.status, 200)
 
